### ISSUE TITLE
Check if images are different

### ISSUE THREAD

**Issue by karlisup** [Apkawa/pytest-image-diff#4]
* pytest-image-diff version: 0.0.8
* Python version: 3.1
* Operating System: macOS Monterey

### Description
Executed
```image_diff(path_to_image_before, path_to_image_after)```
if images are equal error is not thrown, but if the threshold is reached and images are not equal assertation error is thrown "AssertionError: Image not equals!"
Is there a way to check if images are not equal or threshold is _bigger than x_?

I guess I would expect to do something like
```assert image_diff(path_to_image_before, path_to_image_after)```
or just prefix with ```not``` to get the opposite
```assert not image_diff(path_to_image_before, path_to_image_after)```

Thank you in advance!

**Comment by Apkawa** [comment]
Hello
Okay, I also think throwing an exception in a function is a bad idea.
I think implement like as

```python
import pytest

from typing import Union
from PIL import Image

@pytest.fixture(scope="session")
def image_diff_throw_exception() -> bool:
    """
    Set default throw exception. By default - True
    """
    return False

def test_compare(image_diff):
    image: Image or str or bytes = Image.new()
    image2: Image or str or bytes = '/path/to/image.jpeg'
    assert image_diff(image, image2)
    assert image_diff(image, image2, threshold=0.5)
    # Also can check threshold in compare, ie
    assert image_diff(image, image2) < 0.5
    # For different checks in one test
    assert image_diff(image, image2, threshold=0.5, suffix="one")
    # Or without fixture image_diff_throw_exception
    assert image_diff(image, image2, threshold=0.5, throw_exception=False)


def test_regression(image_regression):
    image: Union[Image, str, bytes] = Image.new()
    assert image_regression(image, threshold=0.5)
    # Also can check threshold in compare, ie
    assert image_regression(image) < 0.5
    # For different checks in one test
    assert image_regression(image, threshold=0.5, suffix="foo")
    # Or without fixture image_diff_throw_exception
    assert image_regression(image, threshold=0.5, throw_exception=False)
```

ie for backward compatible add fixture for disabled exception in function. 
in future think maybe make deprecated and turn off exception in next releases

**Comment by karlisup** [comment]
Thank you for the blazing fast support and quick answer! As I noticed the proposed solution PR is still in the review. And the proposed solution should work when the PR is merged, right?

Currently with the same version having same old error, so I just wanted to make sure.
`assert image_diff(path_to_image_before, path_to_star_texture) > 0`
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/3999661/172569913-a1564b3d-c8c5-4c5c-80e7-89679e5bc94e.png">

**Comment by Apkawa** [comment]
I finally finished all the tests and published

`pip install pytest-image-diff==0.0.9`

First you need add into conftest.py fixture setting
```python

@pytest.fixture(scope="session")
def image_diff_throw_exception() -> bool:
    """
    Set default throw exception. By default - True
    """
    return False
```
and  little rewrite your tests

Check it is ok?

**Comment by karlisup** [comment]
At the first glance, everything seems to be working just fine, thank you!
