### ISSUE TITLE
Can you specify or change the .tests directory?

### ISSUE THREAD

**Issue by dborin** [Apkawa/pytest-image-diff#6]
Sorry -- not truly an issue, but there is also no other way to contact you.

Is there a way to change or specify the directory where the failure image comparisons are written, rather than in a local .tests directory, since for me, I already have a tests (no dot) directory that becomes a sibling of your .tests directory.

**Comment by Apkawa** [comment]
Hello.
See https://pytest-image-diff.readthedocs.io/en/latest/code.html#pytest_image_diff.plugin.image_diff_dir
You can add fixture into your conftest.py
 As example:
```python
@pytest.fixture(scope="session")  # pragma: no cover
def image_diff_dir(image_diff_root: str) -> str:

    return os.path.join(image_diff_root, "another_name_for_dot_tests/")
```

**Comment by dborin** [comment]
Thanks so much for the fast reply!

**Comment by dborin** [comment]
I have additional questions.  Is this your preferred way of contact?  If not, my profile has my email address.  Otherwise, let me know and I'll ask more questions here, as issues in Github.

**Comment by Apkawa** [comment]
you can ask questions here it is ok

if there is something confidential you can find my email in setup.py
